### ISSUE TITLE
Double dir in the repo due to case

### ISSUE THREAD

**Issue by lynxlynxlynx** [SpellholdStudios/Fade_NPC#1]
Pretty self-explanatory:
![image](https://user-images.githubusercontent.com/121515/111907496-e3955500-8a55-11eb-925f-c45c41b5bc19.png)

Should be merged back into one to avoid packaging bugs.

**Comment by Gitjas** [comment]
I think I need help with this one. (Inexperienced) Windows user here. :(

**Comment by lynxlynxlynx** [comment]
Easiest if I just do it for you, I guess.

**Comment by Gitjas** [comment]
Thank you!
